const {
    Model,
    DataTypes
} = require('sequelize');
const sequelize = require('../config/connection');


class Comment extends Model {}

Comment.init({
    id: {
        type: DataTypes.INTEGER,
        // needs to be filled in
        allowNull: false,
        //this field is the primary key for the model.
        primaryKey: true,
        //adds 1 to each input
        autoIncrement: true
    },
    comment_text: {
        type: DataTypes.STRING,
        // needs to be filled in
        allowNull: false,
        //only allow 1 comment
        validate: {
            len: [1]
        }
    },
    user_id: {
        type: DataTypes.INTEGER,
        // needs to be filled in
        allowNull: false,
        references: {
            model: 'user',
            key: 'id'
        }
    },
    post_id: {
        type: DataTypes.INTEGER,
        // needs to be filled in
        allowNull: false,
        references: {
            model: 'post',
            key: 'id'
        }
    }
}, {
    sequelize,
    //You can stop the auto-pluralization performed by Sequelize
    freezeTableName: true,
    //This also applies to foreign keys automatically generated by associations and other automatically generated fields.
    underscored: true,
    modelName: 'comment'
})

//can use comment in other files
module.exports = Comment;